FROM ubuntu:18.04
MAINTAINER Rajeev Gadgil <rajeev.gadgil@cavium.com>
RUN apt update
RUN apt install -y --no-install-recommends build-essential 
RUN apt install -y --no-install-recommends libssl-dev libpcre3-dev 
RUN apt install -y --no-install-recommends wget git libev-dev libevent-dev curl ca-certificates
